menu.addItem("Actions", "actions/index-default.html");
    var menuN4000DB = null;
    menuN4000DB = new MTMenu();
    menuN4000DB.addItem("createBuch", "actions/createBuch-default.html");
  menuN4000DB.addItem("createAutor", "actions/createAutor-default.html");
  menuN4000DB.addItem("createKunde", "actions/createKunde-default.html");
  menuN4000DB.addItem("login", "actions/login-default.html");
  menuN4000DB.addItem("fulfillOrder", "actions/fulfillOrder-default.html");
  menu.makeLastSubmenu(menuN4000DB);
  menu.addItem("Data Sources", "data-sources/index-default.html");
    var menuN4000F0 = null;
    menuN4000F0 = new MTMenu();
    menuN4000F0.addItem("DataSource1", "data-sources/-default.html");
  menu.makeLastSubmenu(menuN4000F0);
  menu.addItem("Form Beans", "forms/index-default.html");
    var menuN4000F6 = null;
    menuN4000F6 = new MTMenu();
    menuN4000F6.addItem("buchForm", "forms/buchForm-default.html");
  menuN4000F6.addItem("autorForm", "forms/autorForm-default.html");
  menuN4000F6.addItem("kundeForm", "forms/kundeForm-default.html");
  menuN4000F6.addItem("loginForm", "forms/loginForm-default.html");
  menuN4000F6.addItem("fulfillOrderForm", "forms/fulfillOrderForm-default.html");
  menu.makeLastSubmenu(menuN4000F6);
  menu.addItem("Forwards", "forwards/index-default.html");
    var menuN400108 = null;
    menuN400108 = new MTMenu();
    menuN400108.addItem("buchCreated", "forwards/buchCreated-default.html");
  menuN400108.addItem("autorCreated", "forwards/autorCreated-default.html");
  menuN400108.addItem("kundeCreated", "forwards/kundeCreated-default.html");
  menuN400108.addItem("loginSuccess", "forwards/loginSuccess-default.html");
  menuN400108.addItem("fulfillOrderSuccess", "forwards/fulfillOrderSuccess-default.html");
  menu.makeLastSubmenu(menuN400108);
  menu.addItem("Message Resources");
    var menuN40011A = null;
    menuN40011A = new MTMenu();
    menuN40011A.addItem("Messages1", "message-resources/Messages1-default.html");
  menu.makeLastSubmenu(menuN40011A);
  menu.addItem("Plug-Ins", "plugins/index-default.html");
    var menuN40011F = null;
    menuN40011F = new MTMenu();
    menuN40011F.addItem("org.apache.struts.tiles.TilesPlugin", "plugins/org.apache.struts.tiles.TilesPlugin-default.html");
  menuN40011F.addItem("org.apache.struts.validator.ValidatorPlugIn", "plugins/org.apache.struts.validator.ValidatorPlugIn-default.html");
  menuN40011F.addItem("struts.MyStrutsPlugin", "plugins/struts.MyStrutsPlugin-default.html");
  menu.makeLastSubmenu(menuN40011F);
  menu.addItem("Tiles Definitions", "tiles/index-All.html");
    var menuN40013B = null;
    menuN40013B = new MTMenu();
    menuN40013B.addItem("BasisLayout", "tiles/1-default.html");
  menu.makeLastSubmenu(menuN40013B);
  