menu.addItem("Actions", "actions/index-All.html");
    var menuN400142 = null;
    menuN400142 = new MTMenu();
    menuN400142.addItem("createBuch", "actions/createBuch-default.html");
  menuN400142.addItem("createAutor", "actions/createAutor-default.html");
  menuN400142.addItem("createKunde", "actions/createKunde-default.html");
  menuN400142.addItem("login", "actions/login-default.html");
  menuN400142.addItem("fulfillOrder", "actions/fulfillOrder-default.html");
  menu.makeLastSubmenu(menuN400142);
  menu.addItem("Data Sources", "data-sources/index-All.html");
    var menuN400157 = null;
    menuN400157 = new MTMenu();
    menuN400157.addItem("DataSource1", "data-sources/-default.html");
  menu.makeLastSubmenu(menuN400157);
  menu.addItem("Form Beans", "forms/index-All.html");
    var menuN40015D = null;
    menuN40015D = new MTMenu();
    menuN40015D.addItem("buchForm", "forms/buchForm-default.html");
  menuN40015D.addItem("autorForm", "forms/autorForm-default.html");
  menuN40015D.addItem("kundeForm", "forms/kundeForm-default.html");
  menuN40015D.addItem("loginForm", "forms/loginForm-default.html");
  menuN40015D.addItem("fulfillOrderForm", "forms/fulfillOrderForm-default.html");
  menu.makeLastSubmenu(menuN40015D);
  menu.addItem("Forwards", "forwards/index-All.html");
    var menuN40016F = null;
    menuN40016F = new MTMenu();
    menuN40016F.addItem("buchCreated", "forwards/buchCreated-default.html");
  menuN40016F.addItem("autorCreated", "forwards/autorCreated-default.html");
  menuN40016F.addItem("kundeCreated", "forwards/kundeCreated-default.html");
  menuN40016F.addItem("loginSuccess", "forwards/loginSuccess-default.html");
  menuN40016F.addItem("fulfillOrderSuccess", "forwards/fulfillOrderSuccess-default.html");
  menu.makeLastSubmenu(menuN40016F);
  menu.addItem("Message Resources");
    var menuN400181 = null;
    menuN400181 = new MTMenu();
    menuN400181.addItem("Messages1", "message-resources/Messages1-default.html");
  menu.makeLastSubmenu(menuN400181);
  menu.addItem("Plug-Ins", "plugins/index-All.html");
    var menuN400186 = null;
    menuN400186 = new MTMenu();
    menuN400186.addItem("org.apache.struts.tiles.TilesPlugin", "plugins/org.apache.struts.tiles.TilesPlugin-default.html");
  menuN400186.addItem("org.apache.struts.validator.ValidatorPlugIn", "plugins/org.apache.struts.validator.ValidatorPlugIn-default.html");
  menuN400186.addItem("struts.MyStrutsPlugin", "plugins/struts.MyStrutsPlugin-default.html");
  menu.makeLastSubmenu(menuN400186);
  menu.addItem("Tiles Definitions", "tiles/index-All.html");
    var menuN400193 = null;
    menuN400193 = new MTMenu();
    menuN400193.addItem("BasisLayout", "tiles/1-default.html");
  menu.makeLastSubmenu(menuN400193);
  